env:
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-restricted-syntax: 0,
  import/extensions: 0,
  no-console: 0,
  import/extesions: 0,
}
